#%RAML 1.0
title: API Course Mule Sales Rest
/teste:
  get:
/demo-01:
  /rest:
    get:
  /soap:
    get:
/demo-02:
  /insert:
    post:
/demo-03:
  /consultar:
    post:
/demo-04:
  /batch/v2:
    post:
/demo-05:
  /{id}:
    get: